# Challenge part 1 get weather description and amount of precipitation for each city

In [1]:
from citipy import citipy
import numpy as np
import pandas as pd

In [2]:
# Create a set of random latitudes and longitudes combinations
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats,lngs)

In [3]:
# Add the latitudes and longitudes to a list
coordinates = list(lat_lngs)

In [4]:
# Create a list for holding the cities
cities = []  

#Identify the nearest city for each latitude and longitude combination
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    #If city is unique then add it to cities list
    if city not in cities:
        cities.append(city)
len(cities)

589

In [5]:
# Import request library
import requests

from datetime import datetime

from config import weather_api_key

In [6]:
url = f"http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID={weather_api_key}"

In [17]:
# List of city data 
city_data = []

#Print to logger
print("Beginning Data Retrieval")
print("-" * 25)

#Create a counter
record_count = 1
set_count = 1
for index, city in enumerate(cities):
    
    
    #Group cities in set of 50 for logging purpose
    if(index % 50 == 0 and index >= 50):
        set_count += 1
        record_count = 1
        
    # Create endpoint URL with each city 
    city_url = f'{url}&q={city.replace(" ", "+")}'
    
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    record_count += 1
    
    
    try:
        city_weather = requests.get(city_url).json()
         # Parse out the max temp, humidity, and cloudiness
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_weather_description = city_weather["weather"][0]["description"]
        
        try: 
            city_rain_inches = city_weather["rain"]["1h"]
        except KeyError:
            city_rain_inches = 0
        
        try:
            city_snow_inches = city_weather["snow"]["1h"]
        except KeyError:
            city_snow_inches = 0
        
        # Append the city information to city_data
        city_data.append(
        {
            "City": city, 
            "Lat": city_lat,
            "Lng": city_lng,
            "Max Temp": city_max_temp,
            "Current Description": city_weather_description,
            "Rain (inches)": city_rain_inches,
            "Snow (inches)": city_snow_inches,
            "Humidity": city_humidity,
            "Cloudiness": city_clouds,
            "Wind Speed": city_wind,
            "Country": city_country
        })
    except:
        print("City not found. Skipping...")
        pass
#Indicate that the Data Loading is complete 
print("-" * 20)
print("Data Retrieval Complete")
print("-" * 20)

Beginning Data Retrieval
-------------------------
Processing Record 1 of Set 1 | rikitea
Processing Record 2 of Set 1 | barrow
Processing Record 3 of Set 1 | cartagena
Processing Record 4 of Set 1 | carnarvon
Processing Record 5 of Set 1 | aykhal
Processing Record 6 of Set 1 | laguna
Processing Record 7 of Set 1 | bone
Processing Record 8 of Set 1 | ushuaia
Processing Record 9 of Set 1 | khatanga
Processing Record 10 of Set 1 | adrar
Processing Record 11 of Set 1 | canaries
Processing Record 12 of Set 1 | colac
Processing Record 13 of Set 1 | faanui
Processing Record 14 of Set 1 | iberia
Processing Record 15 of Set 1 | ancud
Processing Record 16 of Set 1 | jieshi
Processing Record 17 of Set 1 | bogovarovo
Processing Record 18 of Set 1 | fairbanks
Processing Record 19 of Set 1 | hobart
Processing Record 20 of Set 1 | troitsko-pechorsk
Processing Record 21 of Set 1 | sao desiderio
Processing Record 22 of Set 1 | ikornnes
Processing Record 23 of Set 1 | punta arenas
Processing Record 24 of Set 1 | hudson bay
Processing Record 25 of Set 1 | inhambane
Processing Record 26 of Set 1 | scarborough
Processing Record 27 of Set 1 | geraldton
Processing Record 28 of Set 1 | castro
Processing Record 29 of Set 1 | la ronge
Processing Record 30 of Set 1 | sept-iles
Processing Record 31 of Set 1 | ketrzyn
Processing Record 32 of Set 1 | vaini
Processing Record 33 of Set 1 | busselton
Processing Record 34 of Set 1 | mar del plata
Processing Record 35 of Set 1 | albany
Processing Record 36 of Set 1 | tuktoyaktuk
Processing Record 37 of Set 1 | qaqortoq
Processing Record 38 of Set 1 | adelaide
Processing Record 39 of Set 1 | vianopolis
Processing Record 40 of Set 1 | chicama
Processing Record 41 of Set 1 | luanda
Processing Record 42 of Set 1 | east london
Processing Record 43 of Set 1 | puerto ayora
Processing Record 44 of Set 1 | linhares
Processing Record 45 of Set 1 | taltal
Processing Record 46 of Set 1 | makubetsu
Processing Record 47 of Set 1 | mataura
Processing Record 48 of Set 1 | naze
Processing Record 49 of Set 1 | ovruch
Processing Record 50 of Set 1 | harper
Processing Record 1 of Set 2 | dikson
Processing Record 2 of Set 2 | kapaa
Processing Record 3 of Set 2 | patacamaya
Processing Record 4 of Set 2 | bengkulu
Processing Record 5 of Set 2 | umzimvubu
City not found. Skipping...
Processing Record 6 of Set 2 | touros
Processing Record 7 of Set 2 | bredasdorp
Processing Record 8 of Set 2 | reconquista
Processing Record 9 of Set 2 | lompoc
Processing Record 10 of Set 2 | voh
Processing Record 11 of Set 2 | hasaki
Processing Record 12 of Set 2 | lagoa
Processing Record 13 of Set 2 | saskylakh
Processing Record 14 of Set 2 | itarema
Processing Record 15 of Set 2 | les cayes
Processing Record 16 of Set 2 | taolanaro
City not found. Skipping...
Processing Record 17 of Set 2 | arraial do cabo
Processing Record 18 of Set 2 | ribeira grande
Processing Record 19 of Set 2 | nizwa
Processing Record 20 of Set 2 | antonina
Processing Record 21 of Set 2 | hermanus
Processing Record 22 of Set 2 | lebu
Processing Record 23 of Set 2 | mbandaka
Processing Record 24 of Set 2 | bluff
Processing Record 25 of Set 2 | axim
Processing Record 26 of Set 2 | deputatskiy
Processing Record 27 of Set 2 | narsaq
Processing Record 28 of Set 2 | port alfred
Processing Record 29 of Set 2 | palabuhanratu
City not found. Skipping...
Processing Record 30 of Set 2 | bosaso
Processing Record 31 of Set 2 | havoysund
Processing Record 32 of Set 2 | kloulklubed
Processing Record 33 of Set 2 | poum
Processing Record 34 of Set 2 | roald
Processing Record 35 of Set 2 | san patricio
Processing Record 36 of Set 2 | tuatapere
Processing Record 37 of Set 2 | namibe
Processing Record 38 of Set 2 | nyurba
Processing Record 39 of Set 2 | akdepe
Processing Record 40 of Set 2 | belushya guba
City not found. Skipping...
Processing Record 41 of Set 2 | katsiveli
City not found. Skipping...
Processing Record 42 of Set 2 | thunder bay
Processing Record 43 of Set 2 | chokurdakh
Processing Record 44 of Set 2 | tsihombe
City not found. Skipping...
Processing Record 45 of Set 2 | tautira
Processing Record 46 of Set 2 | tiksi
Processing Record 47 of Set 2 | korla
Processing Record 48 of Set 2 | maryanovka
City not found. Skipping...
Processing Record 49 of Set 2 | champerico
Processing Record 50 of Set 2 | atuona
Processing Record 1 of Set 3 | cherskiy
Processing Record 2 of Set 3 | atambua
Processing Record 3 of Set 3 | attawapiskat
City not found. Skipping...
Processing Record 4 of Set 3 | prince rupert
Processing Record 5 of Set 3 | okato
Processing Record 6 of Set 3 | florianopolis
Processing Record 7 of Set 3 | butaritari
Processing Record 8 of Set 3 | yeppoon
Processing Record 9 of Set 3 | corinth
Processing Record 10 of Set 3 | zyryanka
Processing Record 11 of Set 3 | pascagoula
Processing Record 12 of Set 3 | katobu
Processing Record 13 of Set 3 | temaraia
City not found. Skipping...
Processing Record 14 of Set 3 | yellowknife
Processing Record 15 of Set 3 | thompson
Processing Record 16 of Set 3 | iwaki
Processing Record 17 of Set 3 | jiddah
City not found. Skipping...
Processing Record 18 of Set 3 | airai
Processing Record 19 of Set 3 | chuy
Processing Record 20 of Set 3 | rawson
Processing Record 21 of Set 3 | kodiak
Processing Record 22 of Set 3 | bandarbeyla
Processing Record 23 of Set 3 | upernavik
Processing Record 24 of Set 3 | oyama
Processing Record 25 of Set 3 | utiel
Processing Record 26 of Set 3 | los llanos de aridane
Processing Record 27 of Set 3 | qaanaaq
Processing Record 28 of Set 3 | umea
Processing Record 29 of Set 3 | avarua
Processing Record 30 of Set 3 | tias
Processing Record 31 of Set 3 | pevek
Processing Record 32 of Set 3 | havre-saint-pierre
Processing Record 33 of Set 3 | bur gabo
City not found. Skipping...
Processing Record 34 of Set 3 | viligili
City not found. Skipping...
Processing Record 35 of Set 3 | hilo
Processing Record 36 of Set 3 | novosokolniki
Processing Record 37 of Set 3 | comodoro rivadavia
Processing Record 38 of Set 3 | sladkovo
Processing Record 39 of Set 3 | dalaba
Processing Record 40 of Set 3 | college
Processing Record 41 of Set 3 | bethel
Processing Record 42 of Set 3 | vanimo
Processing Record 43 of Set 3 | mangrol
Processing Record 44 of Set 3 | kabinda
Processing Record 45 of Set 3 | ahipara
Processing Record 46 of Set 3 | shache
Processing Record 47 of Set 3 | douglas
Processing Record 48 of Set 3 | hinganghat
Processing Record 49 of Set 3 | camopi
Processing Record 50 of Set 3 | ban phai
Processing Record 1 of Set 4 | bilma
Processing Record 2 of Set 4 | georgetown
Processing Record 3 of Set 4 | caxias
Processing Record 4 of Set 4 | lata
Processing Record 5 of Set 4 | centenario do sul
Processing Record 6 of Set 4 | iqaluit
Processing Record 7 of Set 4 | kaitangata
Processing Record 8 of Set 4 | penzance
Processing Record 9 of Set 4 | plastun
Processing Record 10 of Set 4 | nizhneyansk
City not found. Skipping...
Processing Record 11 of Set 4 | sola
Processing Record 12 of Set 4 | new norfolk
Processing Record 13 of Set 4 | richards bay
Processing Record 14 of Set 4 | nome
Processing Record 15 of Set 4 | sentyabrskiy
City not found. Skipping...
Processing Record 16 of Set 4 | haines junction
Processing Record 17 of Set 4 | barentsburg
City not found. Skipping...
Processing Record 18 of Set 4 | jamestown
Processing Record 19 of Set 4 | katsuura
Processing Record 20 of Set 4 | pasni
Processing Record 21 of Set 4 | fortuna
Processing Record 22 of Set 4 | olginskaya
Processing Record 23 of Set 4 | sabinas hidalgo
Processing Record 24 of Set 4 | cape town
Processing Record 25 of Set 4 | bonnyville
Processing Record 26 of Set 4 | weleri
Processing Record 27 of Set 4 | hithadhoo
Processing Record 28 of Set 4 | preobrazheniye
Processing Record 29 of Set 4 | torbay
Processing Record 30 of Set 4 | sirnak
Processing Record 31 of Set 4 | longlac
City not found. Skipping...
Processing Record 32 of Set 4 | alice springs
Processing Record 33 of Set 4 | kavieng
Processing Record 34 of Set 4 | quelimane
Processing Record 35 of Set 4 | nikolskoye
Processing Record 36 of Set 4 | ilulissat
Processing Record 37 of Set 4 | pacific grove
Processing Record 38 of Set 4 | nouadhibou

Processing Record 39 of Set 4 | san lorenzo
Processing Record 40 of Set 4 | faya
Processing Record 41 of Set 4 | port macquarie
Processing Record 42 of Set 4 | dabakala
Processing Record 43 of Set 4 | vaitupu
City not found. Skipping...
Processing Record 44 of Set 4 | pangkalanbuun
Processing Record 45 of Set 4 | hervey bay
Processing Record 46 of Set 4 | shar
Processing Record 47 of Set 4 | mulege
Processing Record 48 of Set 4 | yei
Processing Record 49 of Set 4 | tura
Processing Record 50 of Set 4 | quatre cocos
Processing Record 1 of Set 5 | sur
Processing Record 2 of Set 5 | warmbad
Processing Record 3 of Set 5 | gazanjyk
Processing Record 4 of Set 5 | mutsamudu
City not found. Skipping...
Processing Record 5 of Set 5 | novyy urengoy
Processing Record 6 of Set 5 | phetchabun
Processing Record 7 of Set 5 | dzhusaly
City not found. Skipping...
Processing Record 8 of Set 5 | esperance
Processing Record 9 of Set 5 | planeta rica
Processing Record 10 of Set 5 | mys shmidta
City not found. Skipping...
Processing Record 11 of Set 5 | beringovskiy
Processing Record 12 of Set 5 | kvarkeno
Processing Record 13 of Set 5 | orlik
Processing Record 14 of Set 5 | kabelvag
Processing Record 15 of Set 5 | nuuk
Processing Record 16 of Set 5 | ixtapa
Processing Record 17 of Set 5 | strelka
Processing Record 18 of Set 5 | saint-louis
Processing Record 19 of Set 5 | kharp
Processing Record 20 of Set 5 | marcona
City not found. Skipping...
Processing Record 21 of Set 5 | chepareria
Processing Record 22 of Set 5 | gedo
Processing Record 23 of Set 5 | hofn
Processing Record 24 of Set 5 | dingle
Processing Record 25 of Set 5 | kualakapuas
Processing Record 26 of Set 5 | saldanha
Processing Record 27 of Set 5 | noumea
Processing Record 28 of Set 5 | kruisfontein
Processing Record 29 of Set 5 | waipawa
Processing Record 30 of Set 5 | longyearbyen
Processing Record 31 of Set 5 | nanortalik
Processing Record 32 of Set 5 | vikhorevka
Processing Record 33 of Set 5 | aklavik
Processing Record 34 of Set 5 | bulanash
Processing Record 35 of Set 5 | kerrabe
City not found. Skipping...
Processing Record 36 of Set 5 | saurimo
Processing Record 37 of Set 5 | williams lake
Processing Record 38 of Set 5 | canon city
Processing Record 39 of Set 5 | grand river south east
City not found. Skipping...
Processing Record 40 of Set 5 | longyan
Processing Record 41 of Set 5 | salalah
Processing Record 42 of Set 5 | victoria
Processing Record 43 of Set 5 | san andres
Processing Record 44 of Set 5 | bahile
Processing Record 45 of Set 5 | souillac
Processing Record 46 of Set 5 | novobureyskiy
Processing Record 47 of Set 5 | sidi ali
Processing Record 48 of Set 5 | asfi
Processing Record 49 of Set 5 | tasiilaq
Processing Record 50 of Set 5 | cotonou
Processing Record 1 of Set 6 | puerto del rosario
Processing Record 2 of Set 6 | isoka
Processing Record 3 of Set 6 | sorland
Processing Record 4 of Set 6 | taoudenni
Processing Record 5 of Set 6 | cidreira
Processing Record 6 of Set 6 | olafsvik
Processing Record 7 of Set 6 | patiya
Processing Record 8 of Set 6 | arrecife
Processing Record 9 of Set 6 | saint-philippe
Processing Record 10 of Set 6 | sechura
Processing Record 11 of Set 6 | yar-sale
Processing Record 12 of Set 6 | gat
Processing Record 13 of Set 6 | mount gambier
Processing Record 14 of Set 6 | port lincoln
Processing Record 15 of Set 6 | diego de almagro
Processing Record 16 of Set 6 | smoky lake
Processing Record 17 of Set 6 | gorom-gorom
Processing Record 18 of Set 6 | pangody
Processing Record 19 of Set 6 | novska
Processing Record 20 of Set 6 | jujuy
City not found. Skipping...
Processing Record 21 of Set 6 | isangel
Processing Record 22 of Set 6 | tashtagol
Processing Record 23 of Set 6 | illoqqortoormiut
City not found. Skipping...
Processing Record 24 of Set 6 | kudahuvadhoo
Processing Record 25 of Set 6 | coihueco
Processing Record 26 of Set 6 | robertsport
Processing Record 27 of Set 6 | grindavik
Processing Record 28 of Set 6 | riohacha
Processing Record 29 of Set 6 | sitka
Processing Record 30 of Set 6 | saint-pierre
Processing Record 31 of Set 6 | kununurra
Processing Record 32 of Set 6 | fallon
Processing Record 33 of Set 6 | gavrilov-yam
Processing Record 34 of Set 6 | guerrero negro
Processing Record 35 of Set 6 | clyde river
Processing Record 36 of Set 6 | grand gaube
Processing Record 37 of Set 6 | gumushane
City not found. Skipping...
Processing Record 38 of Set 6 | mehran
Processing Record 39 of Set 6 | sorvag
City not found. Skipping...
Processing Record 40 of Set 6 | saravan
Processing Record 41 of Set 6 | sinnamary
Processing Record 42 of Set 6 | pimentel
Processing Record 43 of Set 6 | nishihara
Processing Record 44 of Set 6 | xining
Processing Record 45 of Set 6 | tiznit
Processing Record 46 of Set 6 | norman wells
Processing Record 47 of Set 6 | san cristobal
Processing Record 48 of Set 6 | terney
Processing Record 49 of Set 6 | port hedland
Processing Record 50 of Set 6 | mahebourg
Processing Record 1 of Set 7 | lunino
Processing Record 2 of Set 7 | tumannyy
City not found. Skipping...
Processing Record 3 of Set 7 | severo-kurilsk
Processing Record 4 of Set 7 | dumas
Processing Record 5 of Set 7 | solnechnyy
Processing Record 6 of Set 7 | kutum
Processing Record 7 of Set 7 | westport
Processing Record 8 of Set 7 | vila franca do campo
Processing Record 9 of Set 7 | ust-ilimsk
Processing Record 10 of Set 7 | kailua
Processing Record 11 of Set 7 | pavlivka
Processing Record 12 of Set 7 | takoradi
Processing Record 13 of Set 7 | cabo san lucas
Processing Record 14 of Set 7 | jinxiang
Processing Record 15 of Set 7 | suluova
Processing Record 16 of Set 7 | coahuayana
Processing Record 17 of Set 7 | nianzishan
Processing Record 18 of Set 7 | daxian
City not found. Skipping...
Processing Record 19 of Set 7 | vostok
Processing Record 20 of Set 7 | port-gentil
Processing Record 21 of Set 7 | loandjili
Processing Record 22 of Set 7 | kachikau
City not found. Skipping...
Processing Record 23 of Set 7 | namatanai
Processing Record 24 of Set 7 | elizabethton
Processing Record 25 of Set 7 | jalu
Processing Record 26 of Set 7 | troitskoye
Processing Record 27 of Set 7 | bonavista
Processing Record 28 of Set 7 | coquimbo
Processing Record 29 of Set 7 | karratha
Processing Record 30 of Set 7 | olovyannaya
Processing Record 31 of Set 7 | urucui
Processing Record 32 of Set 7 | kjollefjord
Processing Record 33 of Set 7 | san jose de ocoa
Processing Record 34 of Set 7 | namie
Processing Record 35 of Set 7 | lopatino
Processing Record 36 of Set 7 | flinders
Processing Record 37 of Set 7 | nehe
Processing Record 38 of Set 7 | husavik
Processing Record 39 of Set 7 | tigil
Processing Record 40 of Set 7 | komsomolskiy
Processing Record 41 of Set 7 | nioro
Processing Record 42 of Set 7 | alta floresta
Processing Record 43 of Set 7 | bargal
City not found. Skipping...
Processing Record 44 of Set 7 | port elizabeth
Processing Record 45 of Set 7 | brae
Processing Record 46 of Set 7 | valparaiso
Processing Record 47 of Set 7 | lavrentiya
Processing Record 48 of Set 7 | malwan
City not found. Skipping...
Processing Record 49 of Set 7 | inuvik
Processing Record 50 of Set 7 | marsaxlokk
Processing Record 1 of Set 8 | maple creek
Processing Record 2 of Set 8 | cayenne
Processing Record 3 of Set 8 | kitob
Processing Record 4 of Set 8 | padang
Processing Record 5 of Set 8 | gulshat
City not found. Skipping...
Processing Record 6 of Set 8 | san quintin
Processing Record 7 of Set 8 | kenai
Processing Record 8 of Set 8 | auki
Processing Record 9 of Set 8 | ostrovnoy
Processing Record 10 of Set 8 | mitsamiouli
Processing Record 11 of Set 8 | vestmannaeyjar
Processing Record 12 of Set 8 | praia da vitoria
Processing Record 13 of Set 8 | lasa
Processing Record 14 of Set 8 | hambantota
Processing Record 15 of Set 8 | hesperia
Processing Record 16 of Set 8 | palmer
Processing Record 17 of Set 8 | umm kaddadah
Processing Record 18 of Set 8 | kismayo
Processing Record 19 of Set 8 | pandan
Processing Record 20 of Set 8 | saint george
Processing Record 21 of Set 8 | hovd
Processing Record 22 of Set 8 | arkhangelsk
Processing Record 23 of Set 8 | tabiauea
City not found. Skipping...
Processing Record 24 of Set 8 | chernyshevskiy

Processing Record 25 of Set 8 | acapulco
Processing Record 26 of Set 8 | yerky
Processing Record 27 of Set 8 | rodrigues alves
Processing Record 28 of Set 8 | calabozo
Processing Record 29 of Set 8 | wagga wagga
Processing Record 30 of Set 8 | homer
Processing Record 31 of Set 8 | antofagasta
Processing Record 32 of Set 8 | tecpan
Processing Record 33 of Set 8 | atbasar
Processing Record 34 of Set 8 | samarai
Processing Record 35 of Set 8 | inongo
Processing Record 36 of Set 8 | villaviciosa
Processing Record 37 of Set 8 | tres arroyos
Processing Record 38 of Set 8 | bambanglipuro
Processing Record 39 of Set 8 | leningradskiy
Processing Record 40 of Set 8 | asayita
City not found. Skipping...
Processing Record 41 of Set 8 | umri
Processing Record 42 of Set 8 | burnie
Processing Record 43 of Set 8 | srivardhan
Processing Record 44 of Set 8 | khislavichi
Processing Record 45 of Set 8 | bayir
Processing Record 46 of Set 8 | marsh harbour
Processing Record 47 of Set 8 | sakaiminato
Processing Record 48 of Set 8 | maningrida
Processing Record 49 of Set 8 | tezu
Processing Record 50 of Set 8 | pangnirtung
Processing Record 1 of Set 9 | banda aceh
Processing Record 2 of Set 9 | vaitape
Processing Record 3 of Set 9 | disa
Processing Record 4 of Set 9 | konongo
Processing Record 5 of Set 9 | biak
Processing Record 6 of Set 9 | vao
Processing Record 7 of Set 9 | marzuq
Processing Record 8 of Set 9 | denpasar
Processing Record 9 of Set 9 | salinas
Processing Record 10 of Set 9 | tortoli
Processing Record 11 of Set 9 | kisangani
Processing Record 12 of Set 9 | ugoofaaru
Processing Record 13 of Set 9 | berdigestyakh
Processing Record 14 of Set 9 | vanavara
Processing Record 15 of Set 9 | alotau
City not found. Skipping...
Processing Record 16 of Set 9 | jaragua
Processing Record 17 of Set 9 | juneau
Processing Record 18 of Set 9 | avera
Processing Record 19 of Set 9 | anito
Processing Record 20 of Set 9 | koboko
Processing Record 21 of Set 9 | bagdarin
Processing Record 22 of Set 9 | port-cartier
Processing Record 23 of Set 9 | foz
Processing Record 24 of Set 9 | loiza
Processing Record 25 of Set 9 | bam
Processing Record 26 of Set 9 | byron bay
Processing Record 27 of Set 9 | maniitsoq
Processing Record 28 of Set 9 | rudsar
Processing Record 29 of Set 9 | illapel
Processing Record 30 of Set 9 | santa lucia
Processing Record 31 of Set 9 | samusu
City not found. Skipping...
Processing Record 32 of Set 9 | dhidhdhoo
Processing Record 33 of Set 9 | enderby
Processing Record 34 of Set 9 | turukhansk
Processing Record 35 of Set 9 | urgut
Processing Record 36 of Set 9 | one hundred mile house
City not found. Skipping...
Processing Record 37 of Set 9 | bambous virieux
Processing Record 38 of Set 9 | constitucion
Processing Record 39 of Set 9 | havelock
Processing Record 40 of Set 9 | bukachacha
Processing Record 41 of Set 9 | phan rang
City not found. Skipping...
Processing Record 42 of Set 9 | zwedru
Processing Record 43 of Set 9 | waitara
Processing Record 44 of Set 9 | saleaula
City not found. Skipping...
Processing Record 45 of Set 9 | san buenaventura
Processing Record 46 of Set 9 | jumla
Processing Record 47 of Set 9 | ewa beach
Processing Record 48 of Set 9 | berlevag
Processing Record 49 of Set 9 | north myrtle beach
Processing Record 50 of Set 9 | panguna
Processing Record 1 of Set 10 | kangaatsiaq
Processing Record 2 of Set 10 | high level
Processing Record 3 of Set 10 | ufa
Processing Record 4 of Set 10 | kindu
Processing Record 5 of Set 10 | podgorica
Processing Record 6 of Set 10 | bilibino
Processing Record 7 of Set 10 | panaba
Processing Record 8 of Set 10 | goderich
Processing Record 9 of Set 10 | mogadishu
Processing Record 10 of Set 10 | hokitika
Processing Record 11 of Set 10 | wajima
Processing Record 12 of Set 10 | yuzhno-kurilsk
Processing Record 13 of Set 10 | meulaboh
Processing Record 14 of Set 10 | narvik
Processing Record 15 of Set 10 | neftekumsk
Processing Record 16 of Set 10 | qujing
Processing Record 17 of Set 10 | roebourne
Processing Record 18 of Set 10 | kavaratti
Processing Record 19 of Set 10 | yerbogachen
Processing Record 20 of Set 10 | alofi
Processing Record 21 of Set 10 | kalmunai
Processing Record 22 of Set 10 | atar
Processing Record 23 of Set 10 | chegdomyn
Processing Record 24 of Set 10 | mindelo
Processing Record 25 of Set 10 | buchanan
Processing Record 26 of Set 10 | svetlyy
Processing Record 27 of Set 10 | hami
Processing Record 28 of Set 10 | kovdor
Processing Record 29 of Set 10 | shenkursk
Processing Record 30 of Set 10 | juifang
City not found. Skipping...
Processing Record 31 of Set 10 | mehamn
Processing Record 32 of Set 10 | saint-joseph
Processing Record 33 of Set 10 | santa rosa
Processing Record 34 of Set 10 | tabou
Processing Record 35 of Set 10 | novo aripuana
Processing Record 36 of Set 10 | votkinsk
Processing Record 37 of Set 10 | leshukonskoye
Processing Record 38 of Set 10 | zhigansk
Processing Record 39 of Set 10 | west wendover
Processing Record 40 of Set 10 | sangar
Processing Record 41 of Set 10 | polur
Processing Record 42 of Set 10 | treinta y tres
Processing Record 43 of Set 10 | baykalovo
Processing Record 44 of Set 10 | broken hill
Processing Record 45 of Set 10 | avigliano
Processing Record 46 of Set 10 | marakkanam
Processing Record 47 of Set 10 | provideniya
Processing Record 48 of Set 10 | surt
Processing Record 49 of Set 10 | ankang
Processing Record 50 of Set 10 | panama city
Processing Record 1 of Set 11 | totma
Processing Record 2 of Set 11 | tome-acu
City not found. Skipping...
Processing Record 3 of Set 11 | evensk
Processing Record 4 of Set 11 | mangan
Processing Record 5 of Set 11 | balikpapan
Processing Record 6 of Set 11 | shiojiri
Processing Record 7 of Set 11 | shablykino
Processing Record 8 of Set 11 | lorengau
Processing Record 9 of Set 11 | zhezkazgan
Processing Record 10 of Set 11 | marsa matruh
Processing Record 11 of Set 11 | dimbokro
Processing Record 12 of Set 11 | koumac
Processing Record 13 of Set 11 | domoni
Processing Record 14 of Set 11 | te anau
Processing Record 15 of Set 11 | chernyshkovskiy
Processing Record 16 of Set 11 | russell
Processing Record 17 of Set 11 | bara
Processing Record 18 of Set 11 | amurzet
Processing Record 19 of Set 11 | rincon
Processing Record 20 of Set 11 | cleburne
Processing Record 21 of Set 11 | karabulak
Processing Record 22 of Set 11 | ipora
Processing Record 23 of Set 11 | maragogi
Processing Record 24 of Set 11 | koryukivka
Processing Record 25 of Set 11 | eidsvag
Processing Record 26 of Set 11 | manjacaze
Processing Record 27 of Set 11 | le havre
Processing Record 28 of Set 11 | tidore
City not found. Skipping...
Processing Record 29 of Set 11 | esso
Processing Record 30 of Set 11 | aurillac
Processing Record 31 of Set 11 | la asuncion
Processing Record 32 of Set 11 | rosarito
Processing Record 33 of Set 11 | ust-uda
Processing Record 34 of Set 11 | igarka
Processing Record 35 of Set 11 | kegayli
City not found. Skipping...
Processing Record 36 of Set 11 | zlatoustovsk
City not found. Skipping...
Processing Record 37 of Set 11 | kihei
Processing Record 38 of Set 11 | ambovombe
Processing Record 39 of Set 11 | nilanga
Processing Record 40 of Set 11 | barentu
Processing Record 41 of Set 11 | omboue
Processing Record 42 of Set 11 | navan
Processing Record 43 of Set 11 | lafiagi
Processing Record 44 of Set 11 | dubasari
Processing Record 45 of Set 11 | batagay
Processing Record 46 of Set 11 | pozo colorado
Processing Record 47 of Set 11 | corn island
Processing Record 48 of Set 11 | oranjemund
Processing Record 49 of Set 11 | pag
Processing Record 50 of Set 11 | bathsheba
Processing Record 1 of Set 12 | talcahuano
Processing Record 2 of Set 12 | khandyga
Processing Record 3 of Set 12 | sirur
Processing Record 4 of Set 12 | broome
Processing Record 5 of Set 12 | cap malheureux
Processing Record 6 of Set 12 | addi ugri
City not found. Skipping...
Processing Record 7 of Set 12 | port hawkesbury
Processing Record 8 of Set 12 | dehloran
Processing Record 9 of Set 12 | belmonte
Processing Record 10 of Set 12 | goundam
Processing Record 11 of Set 12 | latung
Processing Record 12 of Set 12 | campbell river
Processing Record 13 of Set 12 | howard springs

Processing Record 14 of Set 12 | hobyo
Processing Record 15 of Set 12 | oga
Processing Record 16 of Set 12 | wattens
Processing Record 17 of Set 12 | mocoa
Processing Record 18 of Set 12 | boa vista
Processing Record 19 of Set 12 | ponta do sol
Processing Record 20 of Set 12 | chornukhy
Processing Record 21 of Set 12 | okhotsk
Processing Record 22 of Set 12 | pisco
Processing Record 23 of Set 12 | palana
Processing Record 24 of Set 12 | northam
Processing Record 25 of Set 12 | santa maria del oro
Processing Record 26 of Set 12 | bidhuna
Processing Record 27 of Set 12 | tibiri
Processing Record 28 of Set 12 | bolshoy tsaryn
City not found. Skipping...
Processing Record 29 of Set 12 | sao filipe
Processing Record 30 of Set 12 | nadym
Processing Record 31 of Set 12 | safaga
Processing Record 32 of Set 12 | christchurch
Processing Record 33 of Set 12 | hamilton
Processing Record 34 of Set 12 | elat
Processing Record 35 of Set 12 | mae hong son
Processing Record 36 of Set 12 | shipley
Processing Record 37 of Set 12 | ouadda
Processing Record 38 of Set 12 | larsnes
Processing Record 39 of Set 12 | otjimbingwe
--------------------
Data Retrieval Complete
--------------------

In [18]:
len(city_data)

542

In [19]:
# Convert list of dictionaries to a pandas dataframe
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Current Description,Rain (inches),Snow (inches),Humidity,Cloudiness,Wind Speed,Country
0,rikitea,-23.12,-134.97,69.80,overcast clouds,0.00,0,50,99,8.10,PF
1,barrow,71.29,-156.79,35.60,overcast clouds,0.00,0,80,90,6.93,US
2,cartagena,10.40,-75.51,91.40,scattered clouds,0.00,0,63,40,6.93,CO
3,carnarvon,-24.87,113.63,57.20,clear sky,0.00,0,100,0,8.05,AU
4,aykhal,66.00,111.50,64.40,clear sky,0.00,0,45,9,6.71,RU
5,laguna,38.42,-121.42,87.01,clear sky,0.00,0,39,5,4.70,US
6,bone,51.97,12.14,72.00,clear sky,0.00,0,43,0,5.19,DE
7,ushuaia,-54.80,-68.30,33.80,snow,0.00,0,91,75,9.17,AR
8,khatanga,71.97,102.50,66.76,light rain,0.33,0,68,70,7.92,RU
9,adrar,20.50,-10.07,107.71,clear sky,0.00,0,7,0,6.64,MR

In [21]:
city_data_df.columns

Index(['City', 'Cloudiness', 'Country', 'Current Description', 'Humidity',
       'Lat', 'Lng', 'Max Temp', 'Rain (inches)', 'Snow (inches)',
       'Wind Speed'],
      dtype='object')

In [22]:
new_column_order = sorted(city_data_df.columns.tolist())
city_data_df = city_data_df[new_column_order]
city_data_df

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
0,rikitea,99,PF,overcast clouds,50,-23.12,-134.97,69.80,0.0,0,8.10
1,barrow,90,US,overcast clouds,80,71.29,-156.79,35.60,0.0,0,6.93
2,cartagena,40,CO,scattered clouds,63,10.40,-75.51,91.40,0.0,0,6.93
3,carnarvon,0,AU,clear sky,100,-24.87,113.63,57.20,0.0,0,8.05
4,aykhal,9,RU,clear sky,45,66.00,111.50,64.40,0.0,0,6.71
...,...,...,...,...,...,...,...,...,...,...,...
537,mae hong son,100,TH,overcast clouds,87,19.30,97.97,76.28,0.0,0,1.05
538,shipley,2,GB,clear sky,56,53.83,-1.77,73.99,0.0,0,3.00
539,ouadda,98,CF,overcast clouds,89,8.08,22.40,71.28,0.0,0,2.48
540,larsnes,75,NO,broken clouds,72,62.20,5.58,62.60,0.0,0,13.87
541,otjimbingwe,0,NA,clear sky,27,-22.35,16.13,62.67,0.0,0,9.42

In [23]:
city_data_df.dtypes

City                    object
Cloudiness               int64
Country                 object
Current Description     object
Humidity                 int64
Lat                    float64
Lng                    float64
Max Temp               float64
Rain (inches)          float64
Snow (inches)            int64
Wind Speed             float64
dtype: object

In [24]:
raining_cities = city_data_df.loc[city_data_df["Rain (inches)"] > 0]
raining_cities.head()

,City,Cloudiness,Country,Current Description,Humidity,Lat,Lng,Max Temp,Rain (inches),Snow (inches),Wind Speed
8,khatanga,70,RU,light rain,68,71.97,102.50,66.76,0.33,0,7.92
34,albany,11,US,light rain,44,42.60,-73.97,91.99,0.79,0,3.00
37,adelaide,75,AU,shower rain,93,-34.93,138.60,54.00,0.25,0,5.82
48,ovruch,100,UA,light rain,93,51.32,28.80,66.29,0.72,0,6.06
53,bengkulu,99,ID,light rain,89,-3.80,102.27,74.77,0.26,0,7.90

In [25]:
snowing_cities = city_data_df.loc[city_data_df["Snow (inches)"] > 0]
snowing_cities.head()

Empty DataFrame
Columns: [City, Cloudiness, Country, Current Description, Humidity, Lat, Lng, Max Temp, Rain (inches), Snow (inches), Wind Speed]
Index: []

In [26]:
# Create the output file (CSV)
output_data_file = "data/WeatherPy_Database.csv"
city_data_df.to_csv(output_data_file, index_label="City_ID")